# Generated by Django 5.2 on 2025-05-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bericht',
            fields=[
                ('berichtID', models.AutoField(primary_key=True, serialize=False)),
                ('verstuurder', models.CharField(max_length=100)),
                ('verstuurDatum', models.DateField()),
                ('verstuurTijd', models.TimeField()),
                ('tekst', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
