# Generated by Django 5.2 on 2025-05-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berichten',
            fields=[
                ('berichtID', models.AutoField(primary_key=True, serialize=False)),
                ('verstuurder', models.CharField(max_length=100)),
                ('verstuurDatum', models.DateField()),
                ('verstuurTijd', models.TimeField()),
                ('tekst', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meting',
            fields=[
                ('metingID', models.AutoField(primary_key=True, serialize=False)),
                ('afstand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meetDatum', models.DateField()),
                ('meetTijd', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bericht',
        ),
    ]
