# Generated by Django 5.2 on 2025-05-08 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_berichten_meting_delete_bericht'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meting',
            new_name='Metingen',
        ),
    ]
